pre-commit:
  parallel: true
  jobs:
    - name: lint-fix
      run: bun run lint:fix {staged_files}
      stage_fixed: true
    - name: format
      run: bun run format {staged_files}
      stage_fixed: true
